# -*- coding: utf-8 -*-
"""licenta_v5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zx5zmTv6Okita8MbXh6Ec_P0bjT3xx_q

Conectarea cu Drive + descarcarea librarii albumentation
"""

from google.colab import drive
drive.mount('/content/drive')
!pip install albumentations -q

"""Biblioteci"""

import os
import numpy as  np
import matplotlib.pyplot as plt
from PIL import Image
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.models as models
from torch.utils.data import Dataset, DataLoader
from albumentations.pytorch import ToTensorV2
import albumentations as A
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import seaborn as sns

"""Configurare Device"""

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))

"""Maparea Dataset-urilor"""

herlev_path = '/content/drive/MyDrive/database/herlev'
sipak_path = '/content/drive/MyDrive/database/SIPaKMeD'
out_path = '/content/drive/MyDrive/database/dataset_final/'

clase_names= ['NEGATIV', 'LOW_GRADE', 'HIGH_GRADE']
clase_labels_idx= [0, 1 ,2 ]

for c in clase_names:
    os.makedirs(os.path.join(out_path, c), exist_ok=True)

herlev_map = {
    'normal_superficiel': 0,
    'normal_intermediate': 0,
    'normal_columnar': 0,
    'light_dysplastic': 1,
    'moderate_dysplastic': 1,
    'severe_dysplastic': 2,
    'carcinoma_in_situ': 2
}

sipak_map = {
    'im_Superficial-Intermediate': 0,
    'im_Parabasal': 0,
    'im_Metaplastic': 1,
    'im_Koilocytotic': 1,
    'im_Dyskeratotic': 2,

}

"""Configurare Df"""

data_records = []

# HERLEV
for cls in os.listdir(herlev_path):
    cls_path = os.path.join(herlev_path, cls)
    if not os.path.isdir(cls_path):
        continue

    for img in os.listdir(cls_path):
        if img.endswith(('.jpg','.png','.bmp')):
            data_records.append({
                'image_path': os.path.join(cls_path, img),
                'original_label': herlev_map.get(cls, None),
                'dataset_source': 'herlev'
            })

# SIPAK
for cls in os.listdir(sipak_path):
    cropped = os.path.join(sipak_path, cls, 'CROPPED')

    if not os.path.exists(cropped):
        continue

    for img in os.listdir(cropped):
        if img.endswith(('.jpg','.png','.bmp')):
            data_records.append({
                'image_path': os.path.join(cropped, img),
                'original_label': sipak_map.get(cls, None),
                'dataset_source': 'SIPaKMeD'
            })

df = pd.DataFrame(data_records)
df = df.dropna(subset=['original_label'])

print("\nNumar total imagini:", len(df))
print(df['original_label'].value_counts())
print(df.head())

"""Impartirea dataset 70 train 20 validare 10 test"""

from sklearn.model_selection import train_test_split

#prima data impart 80 cu 20
train_val_df, test_df = train_test_split(df, test_size=0.2, stratify=df['original_label'], random_state=42)

#dupa din 80 -> 70 pentru invatare si 10 pentru validare
train_df, val_df = train_test_split(train_val_df, test_size=0.125, stratify=train_val_df['original_label'], random_state=42)

print(f"train: {len(train_df)}, val: {len(val_df)}, test: {len(test_df)}")
print("\nTrain:", len(train_df))
print("Validare:", len(val_df))
print("Test:", len(test_df))

"""Testez daca citeste si afiseaza imaginiile din dataset"""

import random
idx = random.randint(0, len(train_df)-1)
img_ex = train_df.iloc[idx]['image_path']
lable_ex = train_df.iloc[idx]['original_label']

img = Image.open(img_ex).convert("RGB")

plt.imshow(img)
plt.title(clase_names[lable_ex])
plt.axis("off")
plt.show()

"""Tranformari"""

train_transform = A.Compose([
    A.Resize(224, 224),
    A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=1.0), A.HorizontalFlip(p=0.5),A.VerticalFlip(p=0.5),
    A.RandomBrightnessContrast(),
    A.Affine(translate_percent=0.05, scale=(0.9, 1.1), rotate=(-20, 20), p=0.5),
    A.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1, p=0.5),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]), ToTensorV2(),
])

val_transform = A.Compose([
    A.Resize(224, 224),
    A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=1.0),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]), ToTensorV2(),
])

"""Dataset"""

import cv2

class CervicalDataset(Dataset):
    def __init__(self, img_paths, labels, transform=None):
        self.img_paths = img_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        image_path = self.img_paths[idx]
        label = self.labels[idx]
        image = cv2.imread(image_path)

        if image is None:
            print(f"[!] Eroare la incarcarea imaginii: {image_path}. Se va folosi o imagine neagra.")
            image = np.zeros((224, 224, 3), dtype=np.uint8)

        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        if self.transform:

            image = self.transform(image=image)['image']
        return image, torch.tensor(label, dtype=torch.long)

"""Functie de  evaluare a modelului"""

def evaluate_model(model, loader, title, device):
  if len(loader.dataset) == 0:
    print(f"\n[!] Subsetul {title} este gol in acest fold. Se omite evaluare")
    return

  model.eval()
  all_preds=[]
  all_labels=[]
  with torch.no_grad():
      for images, labels in loader:
          images=images.to(device)
          labels=labels.to(device)

          outputs=model(images)
          _, preds= torch.max(outputs,1)

          all_preds.extend(preds.cpu().numpy())
          all_labels.extend(labels.cpu().numpy())

  acc = accuracy_score(all_labels, all_preds)
  from sklearn.metrics import cohen_kappa_score, matthews_corrcoef, roc_auc_score, f1_score
  kappa = cohen_kappa_score(all_labels, all_preds)
  mcc = matthews_corrcoef(all_labels, all_preds)
  f1 = f1_score(all_labels, all_preds, average='macro')
  print("\n" + "="*50)
  print(f"REPORT: {title}")
  print("="*50)
  print(f"Accuratete: {acc:.4f}\n")
  print(f"Cohen's Kappa:   {kappa:.4f}\n")
  print(f"MCC:             {mcc:.4f}\n")
  print(f"F1 Macro:        {f1:.4f}\n")
  print(classification_report( all_labels, all_preds, target_names=clase_names ))

  cm = confusion_matrix(all_labels, all_preds, labels=clase_labels_idx, normalize='true')
  plt.figure(figsize=(7, 5))
  sns.heatmap(cm, annot=True, fmt='.2f', cmap='Blues', xticklabels=clase_names, yticklabels=clase_names)
  plt.title(f'Matrice de Confuzie - {title}')
  plt.ylabel('Etichete Reale')
  plt.xlabel('Predicții Model')
  plt.xticks(rotation=45)
  plt.show()

"""Compaartie modele"""

import timm
from sklearn.model_selection import StratifiedKFold
from sklearn.utils.class_weight import compute_class_weight
from tqdm.auto import tqdm

labels = df['original_label'].values

model_names = ['efficientnet_b0', 'resnet50', 'inception_v3', 'densenet121']
results = {}
train_df, val_df = train_test_split( df, test_size=0.2, stratify=df['original_label'], random_state=42)

print(f"Train: {len(train_df)}")
print(f"Validation: {len(val_df)}")


for model_name in model_names:
    print(f"\n{'='*60}")
    print(f"MODEL: {model_name}")
    print(f"{'='*60}")


    # dataloaders
    train_loader = DataLoader(
        CervicalDataset(train_df['image_path'].values,
                        train_df['original_label'].values,
                        transform=train_transform),
        batch_size=32, shuffle=True )

    val_loader = DataLoader(
        CervicalDataset(val_df['image_path'].values,
                        val_df['original_label'].values,
                        transform=val_transform),
        batch_size=32, shuffle=False )

    # class weights
    y_train = train_df['original_label'].values
    class_weights = compute_class_weight( class_weight='balanced', classes=np.unique(y_train), y=y_train )
    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device);

    # model
    model = timm.create_model(model_name, pretrained=True, num_classes=len(clase_names))
    model = model.to(device)

    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

    epochs = 10
    best_loss = float('inf')
    # current_best_model_path = f"{model_name}_fold{fold+1}.pth" # 'fold' is not defined in this context
    current_best_model_path = f"{model_name}_best_model.pth"

    train_losses = []
    val_losses = []
    # TRAIN LOOP
    for epoch in range(epochs):
        model.train()
        train_loss = 0.0

        for images, batch_labels in tqdm(train_loader,
                                         desc=f" {model_name} - Epoch {epoch+1}/{epochs} [Train]",
                                         leave=False):

            images = images.to(device)
            batch_labels = batch_labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, batch_labels)

            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        # VALIDATION
        model.eval()
        val_loss = 0.0

        with torch.no_grad():
            for images, batch_labels in val_loader:
                images = images.to(device)
                batch_labels = batch_labels.to(device)

                outputs = model(images)
                loss = criterion(outputs, batch_labels)

                val_loss += loss.item()

        train_loss /= len(train_loader)
        val_loss   /= len(val_loader)


        print(f"{model_name}  Epoch {epoch+1} | "
              f"Train: {train_loss:.4f} | Val: {val_loss:.4f}")

        # save best
        if val_loss < best_loss:
           best_loss = val_loss
           torch.save(model.state_dict(), current_best_model_path)


    print("\nEvaluare finala...")

    model.load_state_dict(torch.load(current_best_model_path))

    evaluate_model(model, val_loader, f"{model_name} - Validation", device)

    results[model_name] = {
        'best_val_loss': best_loss
    }


# rezultate finale

print("\nREZULTATE FINALE")

for model_name, values in results.items():

    print(
        f"{model_name} -> "
        f"Best Validation Loss: {values['best_val_loss']:.4f}"
        # f"Mean Loss: {values['mean_loss']:.4f} | "
        # f"STD: {values['std']:.4f}"
    )

print("\nfinalizat")

"""Aleg cel mai bun clasificator Resnet50


Executie principala cu Pure K-FOLD dupa exemplu stefanei
"""

labels = df['original_label'].values

from sklearn.model_selection import StratifiedKFold
from sklearn.utils.class_weight import compute_class_weight
from tqdm.auto import tqdm

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for fold, (train_idx, val_idx) in enumerate(skf.split(df, labels)):

    print(f"\n{'#'*50}")
    print(f"FOLD {fold+1}")
    print(f"{'#'*50}")
#impartire date pt fold ul curent
    train_df = df.iloc[train_idx]
    val_df   = df.iloc[val_idx]
#creeem dataloaders
    train_loader = DataLoader( CervicalDataset(train_df['image_path'].values, train_df['original_label'].values, transform=train_transform), batch_size=32, shuffle=True  )
    val_loader = DataLoader( CervicalDataset(val_df['image_path'].values, val_df['original_label'].values, transform=val_transform), batch_size=32, shuffle=False  )
#ponderi pt clase, bazate doar pe train ul curent
    y_train = train_df['original_label'].values
    class_weights = compute_class_weight( class_weight='balanced', classes=np.unique(y_train), y=y_train   )
    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)
#model pt fiecare fold
    model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
    model.fc=nn.Linear(model.fc.in_features, len(clase_names))
    model = model.to(device)
#model.classifier = nn.Linear(model.classifier.in_features, len(clase_names))


    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)
    #optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
    optimizer = torch.optim.Adam( model.parameters(), lr=5e-5, weight_decay=1e-4 )
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau( optimizer, mode='min', factor=0.5, patience=2 )
    epochs = 15
    #pt early stopping
    patience = 4
    counter = 0
    best_loss = float('inf')

    best_model_path_save = f'/content/drive/MyDrive/licenta/best_model_fold_{fold+1}.pth'
    os.makedirs(os.path.dirname(best_model_path_save), exist_ok=True)
    train_losses = [] # pt plot grafice
    val_losses = []
    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for images, labels in tqdm(train_loader, desc=f"Fold {fold+1} - Epoch {epoch+1}/{epochs} [Train]", leave=False):

            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)

            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        # eval simpla pt loss ca sa +salvare bestmodel
        model.eval()
        val_loss = 0

        with torch.no_grad():
            for images, labels in val_loader:
                images = images.to(device)
                labels = labels.to(device)

                outputs = model(images)
                loss = criterion(outputs, labels)

                val_loss += loss.item()

        train_loss /= len(train_loader)
        val_loss /= len(val_loader)
        #adaugat nou
        scheduler.step(val_loss)

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        print(f"Epoch {epoch+1} | Train: {train_loss:.4f} | Val: {val_loss:.4f}")


    print("\nEvaluare fold...")
    model.load_state_dict(torch.load(best_model_path_save))

    evaluate_model(model, val_loader, f"Fold {fold+1}", device)
    plt.figure(figsize=(8,5))

    plt.plot(train_losses, marker='*', label='Train Loss')
    plt.plot(val_losses, marker='p', label='Validation Loss')

    plt.title(f'Curba Loss - Fold {fold+1}')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')

    plt.legend()
    plt.grid()

    plt.show()

print("\n Gata")

"""Evaluare pe test"""

test_dataset = CervicalDataset( test_df['image_path'].values, test_df['original_label'].values, transform=val_transform )

test_loader = DataLoader( test_dataset, batch_size=32, shuffle=False )

print("\nEvaluare  pe test set")

model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
model.fc = nn.Linear(model.fc.in_features, len(clase_names))
model.load_state_dict( torch.load( "/content/drive/MyDrive/licenta/best_model_fold_1.pth" ) )
model = model.to(device)
model.eval()
print("\nEvaluare fold...")
evaluate_model( model, test_loader, "Dataset Privat", device )

"""Dupa antrenare resnet50 pe sipak si herlev salvez modelul si il antrenez si pe cric

Citire si afisare celule din imaginile din cric
"""

import pandas as pd
import os

csv_path = "/content/drive/MyDrive/cric/classifications.csv"
cric_path = "/content/drive/MyDrive/cric/images"

df = pd.read_csv(csv_path)

cric_map = {
    'Negative for intraepithelial lesion': 0,
    'LSIL': 1,
    'ASC-US': 1,
    'HSIL': 2,
    'ASC-H': 2,
    'SCC': 2
}

df["label"] = df["bethesda_system"].map(cric_map)

df = df.dropna(subset=["label"])

df = df[["image_filename", "label", "nucleus_x", "nucleus_y"]]

df = df.drop_duplicates()

df["image_path"] = df["image_filename"].apply( lambda x: os.path.join(cric_path, x) )

print(df.head())
print(df["label"].value_counts())

idx = random.randint(0, len(df) - 1)
row = df.iloc[idx]

view_img = row['image_path']
view_label = row['label']
nucleus_x = row['nucleus_x']
nucleus_y = row['nucleus_y']

crop_size = 224
half_crop = crop_size // 2

full_image = cv2.imread(view_img)

if full_image is None:
    print(f"[!] Eroare citire imagine {view_img}")
else:
    h, w, _ = full_image.shape

    x1 = int(max(0, nucleus_x - half_crop))
    y1 = int(max(0, nucleus_y - half_crop))
    x2 = int(min(w, nucleus_x + half_crop))
    y2 = int(min(h, nucleus_y + half_crop))

    if x2 - x1 < crop_size:
        x1 = max(0, x2 - crop_size)
    if y2 - y1 < crop_size:
        y1 = max(0, y2 - crop_size)

    cropped_image = full_image[y1:y2, x1:x2]

    cropped_image_rgb = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(6, 6))
    plt.imshow(cropped_image_rgb)
    plt.title(f"Celula adnotata CRIC \nLabel: {clase_names[view_label]}\nCoordonate: ({int(nucleus_x)}, {int(nucleus_y)})")
    plt.axis('off')
    plt.show()

"""Cric dataset antrenare model pe 2 foldere 15 epoci"""

from sklearn.model_selection import StratifiedKFold
from sklearn.utils.class_weight import compute_class_weight
from tqdm.auto import tqdm

labels = df['label'].values

skf = StratifiedKFold(  n_splits=3,  shuffle=True,  random_state=42)


for fold, (train_idx, val_idx) in enumerate(skf.split(df, labels)):

    print(f"\n{'#'*50}")
    print(f"FOLD {fold+1}")
    print(f"{'#'*50}")


    train_df = df.iloc[train_idx]
    val_df = df.iloc[val_idx]
    train_loader = DataLoader( CervicalDataset( train_df['image_path'].values, train_df['label'].values, transform=train_transform ),
                              batch_size=32, shuffle=True)
    val_loader = DataLoader( CervicalDataset(  val_df['image_path'].values,  val_df['label'].values,  transform=val_transform ),
                              batch_size=32,  shuffle=False )

    y_train = train_df['label'].values

    class_weights = compute_class_weight( class_weight='balanced', classes=np.unique(y_train), y=y_train )
    class_weights_tensor = torch.tensor(  class_weights, dtype=torch.float  ).to(device)
    model = models.resnet50(weights=None)
    model.fc = nn.Linear(  model.fc.in_features,  len(clase_names) )
    model.load_state_dict( torch.load(  "/content/drive/MyDrive/licenta/best_model_fold_1.pth"   ))
    model = model.to(device)

    print("\nModel incarcat.")

    criterion = nn.CrossEntropyLoss(  weight=class_weights_tensor )
    optimizer = torch.optim.Adam( model.parameters(), lr=1e-5, weight_decay=1e-4  )
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(  optimizer,  mode='min',  factor=0.5,  patience=2 )

    epochs = 15

    patience = 4
    counter = 0
    best_loss = float('inf')
    best_model_path_save = ( f'/content/drive/MyDrive/licenta/' f'best_cric_fold_{fold+1}.pth' )

    os.makedirs( os.path.dirname(best_model_path_save), exist_ok=True )

    train_losses = []
    val_losses = []


    for epoch in range(epochs):

        model.train()

        train_loss = 0.0

        for images, labels in tqdm( train_loader, desc=f"Fold {fold+1} - Epoch {epoch+1}/{epochs} [Train]" ):
            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)

            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        # eval simpla pt loss +salvare bestmodel
        model.eval()
        val_loss = 0

        with torch.no_grad():
            for images, labels in val_loader:
                images = images.to(device)
                labels = labels.to(device)

                outputs = model(images)
                loss = criterion(outputs, labels)

                val_loss += loss.item()

        train_loss /= len(train_loader)
        val_loss /= len(val_loader)
        #adaugat nou
        scheduler.step(val_loss)

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        print(f"Epoch {epoch+1} | Train: {train_loss:.4f} | Val: {val_loss:.4f}")

        if val_loss < best_loss:
            best_loss = val_loss
            counter = 0
            torch.save(model.state_dict(), best_model_path_save)

        else:
            counter += 1

        if counter >= patience:
            print("Early stopping activat")
            break



#pt fiecare fold sa afca si grafic pt loss

    print("\nEvaluare fold...")
    model.load_state_dict(torch.load(best_model_path_save))

    evaluate_model(model, val_loader, f"Fold {fold+1}", device)
    plt.figure(figsize=(8,5))

    plt.plot(train_losses, marker='*', label='Train Loss')
    plt.plot(val_losses, marker='p', label='Validation Loss')

    plt.title(f'Curba Loss - Fold {fold+1}')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')

    plt.legend()
    plt.grid()

    plt.show()

print("\n Gata")

"""Aleg cel mai bun clasificator (best_model_fold) al lui Resnet50

Fac testarea pe Datasetul cu celule adnotate (clasificari_crop)
"""

import os
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import models

adnotate_path = "/content/drive/MyDrive/clasificare_crop"

# Bethesda:
# 0 = NILM
# 1 = LSIL
# 2 = HSIL

adnotate_map = {
    # NILM
    'no-sq-sup': 0,
    'no-sq-int': 0,
    'no-sq-baz': 0,
    'no-gl-enc': 0,

    # LSIL
    'dz-sq-sup': 1,
    'dz-sq-int': 1,

    # HSIL
    'dz-sq-baz': 2,
    'dz-gl-enc': 2,
}

class_names = [
    "NEGATIV",
    "LOW_GRADE",
    "HIGH_GRADE"
]

data_records = []

for root, dirs, files in os.walk(adnotate_path):

    if "artefacte" in root.lower() or "metaplazii" in root.lower():
        continue

    for img_name in files:

        if not img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            continue
        filename = os.path.splitext(img_name)[0]
        try:
            parts = filename.split("_")
            if len(parts) < 4:
                print(f"Nume invalid: {img_name}")
                continue
            original_label = parts[-1]
            if original_label not in adnotate_map:
                print(f"Eticheta necunoscuta: {img_name}")
                continue
            data_records.append({
                "image_path": os.path.join(root, img_name),
                "label": adnotate_map[original_label],
                "original_label": original_label
            })
        except Exception as e:
            print(f"Eroare la {img_name}: {e}")

df_adnotate = pd.DataFrame(data_records)

print("\nPrimele inregistrari:")
print(df_adnotate.head())

print("\nNumar total imagini:")
print(len(df_adnotate))

print("\nDistributie Bethesda:")
print(df_adnotate["label"].value_counts().sort_index())

print("\nDistributie:")
print(df_adnotate["original_label"].value_counts())


adnotate_dataset = CervicalDataset( df_adnotate["image_path"].values, df_adnotate["label"].values, transform=val_transform )

adnotate_loader = DataLoader(  adnotate_dataset, batch_size=32, shuffle=False )
#testare model deja preantreant
model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
model.fc = nn.Linear(model.fc.in_features, len(class_names))
odel.load_state_dict( torch.load( "/content/drive/MyDrive/licenta/best_model_fold_1.pth" ) )m
model = model.to(device)
model.eval()
print("\nEvaluare fold...")
evaluate_model( model, adnotate_loader, "Dataset Privat", device )

print("\n Gata")

"""Din cauza ca datele din setul de date nu sunt echilibrate o sa facem o augmumentare mai agresiva pentru clasele minoritare cum sunt LOW_Grade si High_grade"""

from tqdm.auto import tqdm
from sklearn.model_selection import train_test_split

X = df_adnotate["image_path"].values
y = df_adnotate["label"].values

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, stratify=y, random_state=42 )

print("\nTrain:", len(X_train))
print("Test:", len(X_test))


# tranformari

train_transform = A.Compose([
    A.RandomResizedCrop((224, 224), scale=(0.8, 1.0), p=0.5), A.Resize(224, 224),
    A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=1.0),
    A.HorizontalFlip(p=0.5), A.VerticalFlip(p=0.5),
    A.Affine(rotate=(-15, 15), scale=(0.9, 1.1), translate_percent=0.05, p=0.5),
    A.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.05, p=0.2),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

# Augmentare mai agresiva pentru clasele rare (LOW_GRADE, HIGH_GRADE)
minority_transform = A.Compose([
    A.RandomResizedCrop((224, 224), scale=(0.7, 1.0), p=0.8), A.Resize(224, 224),
    A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=1.0),
    A.HorizontalFlip(p=0.5), A.VerticalFlip(p=0.5),
    A.Affine(rotate=(-30, 30), scale=(0.85, 1.15), translate_percent=0.08, p=0.7),
    A.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1, p=0.5), A.GaussNoise(p=0.3),
    A.ElasticTransform(p=0.3),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

val_transform = A.Compose([
    A.Resize(224, 224), A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=1.0),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

# dataset special

class ClasificareCropDataset(Dataset):
    def __init__(self, img_paths, labels, transform=None, minority_transform=None):
        self.img_paths = img_paths
        self.labels = labels
        self.transform = transform
        self.minority_transform = minority_transform

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        image = cv2.imread(self.img_paths[idx])
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        label = self.labels[idx]

        # Clase rare => augmentare mai puternica
        if self.minority_transform and label in [1, 2]:
            image = self.minority_transform(image=image)["image"]
        elif self.transform:
            image = self.transform(image=image)["image"]

        return image, torch.tensor(label, dtype=torch.long)

  # weighted sampler —  pentru dezechilibru de clase
from torch.utils.data import WeightedRandomSampler

class_counts = np.bincount(y_train)
class_weights = 1.0 / class_counts
# test sample_weights = np.where(y_train == 1, class_weights[y_train] * 4, np.where(y_train == 2, class_weights[y_train] * 2, class_weights[y_train])) #incerc sa dublez high_grade
sample_weights =  np.where(y_train == 2, class_weights[y_train] * 2, class_weights[y_train]) #incerc sa dublez high_grade
sampler = WeightedRandomSampler( weights=torch.tensor(sample_weights, dtype=torch.float), num_samples=len(sample_weights), replacement=True )

trainset = ClasificareCropDataset( img_paths=X_train, labels=y_train, transform=train_transform, minority_transform=minority_transform )
testset = ClasificareCropDataset( img_paths=X_test, labels=y_test, transform=val_transform )

trainloader = DataLoader(trainset, batch_size=32, sampler=sampler)
testloader  = DataLoader(testset,  batch_size=32, shuffle=False)


model = models.resnet50(weights=None)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, len(class_names))

model.load_state_dict( torch.load( "/content/drive/MyDrive/licenta/best_model_fold_1.pth" ) )

model = model.to(device)
print("\nModel incarcat.")


class FocalLoss(nn.Module):

    def __init__(self, alpha=1, gamma=2):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, inputs, targets):

        ce_loss = nn.CrossEntropyLoss(
            reduction='none'
        )(inputs, targets)

        pt = torch.exp(-ce_loss)

        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss

        return focal_loss.mean()

criterion = FocalLoss(alpha=1, gamma=2)

optimizer = torch.optim.Adam (model.parameters(), lr=1e-5, weight_decay=1e-4 )
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau( optimizer, mode='min', factor=0.5, patience=2 )


best_loss = float("inf")
patience = 4
counter = 0


epochs = 15
train_losses = []
val_losses = []
for epoch in range(epochs):

    model.train()
    train_loss = 0
    for images, labels in tqdm( trainloader,  desc=f"Epoch {epoch+1}/{epochs}"  ):

        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()


    model.eval()
    val_loss = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for images, labels in testloader:
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)
            val_loss += loss.item()
            _, preds = torch.max(outputs,1)
            all_preds.extend(  preds.cpu().numpy())
            all_labels.extend( labels.cpu().numpy() )



    train_loss /= len(trainloader)
    val_loss /= len(testloader)
    train_losses.append(train_loss)
    val_losses.append(val_loss)
    scheduler.step(val_loss)
    print( f"Epoch {epoch+1} | " f"Train: {train_loss:.4f} | " f"Val: {val_loss:.4f}"  )



    if val_loss < best_loss:
        best_loss = val_loss
        counter = 0
        torch.save( model.state_dict(),"best_private_finetuned.pth"  )

    else:
        counter += 1
        if counter >= patience:
            print("\nEarly stopping activat.")
            break

# Define best_model_path_save for final evaluation
best_model_path_save = "best_private_finetuned.pth"

print("\nEvaluare ...")
model.load_state_dict(torch.load(best_model_path_save))

evaluate_model(model, testloader, "Fine-tuned Model Evaluation", device)
plt.figure(figsize=(8,5))

plt.plot(train_losses, marker='*', label='Train Loss')
plt.plot(val_losses, marker='p', label='Validation Loss')

plt.title(f'Curba Loss - Fine-tuned Model')
plt.xlabel('Epoch')
plt.ylabel('Loss')

plt.legend()
plt.grid()

plt.show()

print("\n Gata")

"""incerc sa 4*low_grade si 2*high_grade grade pe mai multe epoci"""

import os
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import models

adnotate_path = "/content/drive/MyDrive/clasificare_crop"

# Bethesda:
# 0 = NILM
# 1 = LSIL
# 2 = HSIL

adnotate_map = {
    # NILM
        'no-sq-sup': 0,
    'no-sq-int': 0,
    'no-sq-int': 0,
    'no-sq-baz': 0,
    'no-gl-enc': 0,

    # LSIL
    'dz-sq-sup': 1,
    'dz-sq-int': 1,

    # HSIL
    'dz-sq-baz': 2,
    'dz-gl-enc': 2,
}


data_records = []

for root, dirs, files in os.walk(adnotate_path):

    if "artefacte" in root.lower() or "metaplazii" in root.lower():
        continue

    for img_name in files:

        if not img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            continue
        filename = os.path.splitext(img_name)[0]
        try:
            parts = filename.split("_")
            if len(parts) < 4:
                print(f"Nume invalid: {img_name}")
                continue
            original_label = parts[-1]
            if original_label not in adnotate_map:
                print(f"Eticheta necunoscuta: {img_name}")
                continue
            data_records.append({
                "image_path": os.path.join(root, img_name),
                "label": adnotate_map[original_label],
                "original_label": original_label
            })
        except Exception as e:
            print(f"Eroare la {img_name}: {e}")

df_adnotate = pd.DataFrame(data_records)

print("\nPrimele inregistrari:")
print(df_adnotate.head())

print("\nNumar total imagini:")
print(len(df_adnotate))

print("\nDistributie Bethesda:")
print(df_adnotate["label"].value_counts().sort_index())

print("\nDistributie:")
print(df_adnotate["original_label"].value_counts())

from tqdm.auto import tqdm
from sklearn.model_selection import train_test_split

X = df_adnotate["image_path"].values
y = df_adnotate["label"].values

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, stratify=y, random_state=42 )

print("\nTrain:", len(X_train))
print("Test:", len(X_test))


# tranformari

train_transform = A.Compose([
    A.RandomResizedCrop((224, 224), scale=(0.8, 1.0), p=0.5), A.Resize(224, 224),
    A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=1.0),
    A.HorizontalFlip(p=0.5), A.VerticalFlip(p=0.5),
    A.Affine(rotate=(-15, 15), scale=(0.9, 1.1), translate_percent=0.05, p=0.5),
    A.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.05, p=0.2),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

# Augmentare mai agresiva pentru clasele rare (LOW_GRADE, HIGH_GRADE)
minority_transform = A.Compose([
    A.RandomResizedCrop((224, 224), scale=(0.7, 1.0), p=0.8), A.Resize(224, 224),
    A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=1.0),
    A.HorizontalFlip(p=0.5), A.VerticalFlip(p=0.5),
    A.Affine(rotate=(-30, 30), scale=(0.85, 1.15), translate_percent=0.08, p=0.7),
    A.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1, p=0.5), A.GaussNoise(p=0.3),
    A.ElasticTransform(p=0.3),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

val_transform = A.Compose([
    A.Resize(224, 224), A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=1.0),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

# dataset special

class ClasificareCropDataset(Dataset):
    def __init__(self, img_paths, labels, transform=None, minority_transform=None):
        self.img_paths = img_paths
        self.labels = labels
        self.transform = transform
        self.minority_transform = minority_transform

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        image = cv2.imread(self.img_paths[idx])
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        label = self.labels[idx]

        if self.minority_transform and label in [1, 2]:
            image = self.minority_transform(image=image)["image"]
        elif self.transform:
            image = self.transform(image=image)["image"]

        return image, torch.tensor(label, dtype=torch.long)

  # weighted sampler   pentru dezechilibru de clase
from torch.utils.data import WeightedRandomSampler

class_counts = np.bincount(y_train)
class_weights = 1.0 / class_counts
sample_weights = np.where(y_train == 1, class_weights[y_train] * 4, np.where(y_train == 2, class_weights[y_train] * 2, class_weights[y_train])) #incerc sa dublez high_grade
sampler = WeightedRandomSampler( weights=torch.tensor(sample_weights, dtype=torch.float), num_samples=len(sample_weights), replacement=True )

trainset = ClasificareCropDataset( img_paths=X_train, labels=y_train, transform=train_transform, minority_transform=minority_transform )
testset = ClasificareCropDataset( img_paths=X_test, labels=y_test, transform=val_transform )

trainloader = DataLoader(trainset, batch_size=32, sampler=sampler)
testloader  = DataLoader(testset,  batch_size=32, shuffle=False)


model = models.resnet50(weights=None)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, len(class_names))

model.load_state_dict( torch.load( "/content/drive/MyDrive/licenta/best_model_fold_1.pth" ) )

model = model.to(device)
print("\nModel incarcat.")


class FocalLoss(nn.Module):

    def __init__(self, alpha=1, gamma=2):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, inputs, targets):

        ce_loss = nn.CrossEntropyLoss(
            reduction='none'
        )(inputs, targets)

        pt = torch.exp(-ce_loss)

        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss

        return focal_loss.mean()

criterion = FocalLoss(alpha=1, gamma=2)

optimizer = torch.optim.Adam (model.parameters(), lr=1e-5, weight_decay=1e-4 )
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau( optimizer, mode='min', factor=0.5, patience=2 )



best_loss = float("inf")
patience = 4
counter = 0


epochs = 35
train_losses = []
val_losses = []
for epoch in range(epochs):

    model.train()
    train_loss = 0
    for images, labels in tqdm( trainloader,  desc=f"Epoch {epoch+1}/{epochs}"  ):

        images = images.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()


    model.eval()
    val_loss = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for images, labels in testloader:
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)
            val_loss += loss.item()
            _, preds = torch.max(outputs,1)
            all_preds.extend(  preds.cpu().numpy())
            all_labels.extend( labels.cpu().numpy() )



    train_loss /= len(trainloader)
    val_loss /= len(testloader)
    train_losses.append(train_loss)
    val_losses.append(val_loss)
    scheduler.step(val_loss)
    print( f"Epoch {epoch+1} | " f"Train: {train_loss:.4f} | " f"Val: {val_loss:.4f}"  )



    if val_loss < best_loss:
        best_loss = val_loss
        counter = 0
        torch.save( model.state_dict(),"best_private_finetuned.pth"  )

    else:
        counter += 1
        if counter >= patience:
            print("\nEarly stopping activat.")
            break

best_model_path_save = "best_private_finetuned.pth"

print("\nEvaluare ...")
model.load_state_dict(torch.load(best_model_path_save))

evaluate_model(model, testloader, "Fine-tuned Model Evaluation", device)
plt.figure(figsize=(8,5))

plt.plot(train_losses, marker='*', label='Train Loss')
plt.plot(val_losses, marker='p', label='Validation Loss')

plt.title(f'Curba Loss - Fine-tuned Model')
plt.xlabel('Epoch')
plt.ylabel('Loss')

plt.legend()
plt.grid()

plt.show()

print("\n Gata")
